"""Copy a solver snapshot to a standalone export directory."""
from __future__ import annotations

import shutil
from pathlib import Path

_README = """# Exported EVRPTW solver

Generated by EVRPTW-AutoLab. No LLM calls are required at runtime.

```python
from solver import solve
# `instance` is an EVRPTWInstance from evrptw_autolab.problem
solution = solve(instance, seed=0, time_limit_s=10.0)
```
"""


def export_solver(solver_dir: Path, output: Path) -> Path:
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)
    for path in solver_dir.rglob("*.py"):
        target = output / path.relative_to(solver_dir)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target)
    (output / "README.md").write_text(_README, encoding="utf-8")
    return output
